global:
  scrape_interval: 15s
rule_files:
  - 'rule.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['host.docker.internal:9093']
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8082']
