groups:
  - name: example
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 20s
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 20 seconds."
